<?php

namespace App\Filament\Resources\InvoiceResource\Pages;

use App\Filament\Resources\InvoiceResource;
use App\Models\PatientRfidPoint;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateInvoice extends CreateRecord
{
    protected static string $resource = InvoiceResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id'] = auth()->id();
        return $data; // TODO: Change the autogenerated stub
    }

    public function afterCreate()
    {
        $data = [];
        // $data['discount'] = collect($this->getRecord()->invoicesItems)->sum(function ($item) {
        //     return $item->discount * $item->qty;
        // });
        $data['vat'] = collect($this->getRecord()->invoicesItems)->sum(function ($item) {
            return $item->vat * $item->qty;
        });
        // $data['total'] = collect($this->getRecord()->invoicesItems)->sum('total');

        if (!empty($this->data['use_rfid_discount']) && $this->data['use_rfid_discount'] == true && !empty($this->data['rfid_number'])) {
            $rfidPoints = PatientRfidPoint::where('rfid_number', $this->data['rfid_number'])->delete();
        }

        $this->getRecord()->update($data);

        $this->getRecord()->invoiceLogs()->create([
            'log' => "Invoice created By: " . auth()->user()->name,
            'type' => 'created'
        ]);

    }
}
